### PR TITLE
Add support for https://liberty-pool.com

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@garrylachman Please consider merging this pull request

**Comment by garrylachman** [comment]
Please merge rebase with main and update PR. there are a lot of changes...

**Comment by ghost** [comment]
> Please merge rebase with main and update PR. there are a lot of changes...

PR updated.

**Comment by garrylachman** [comment]
can you please create a PR to develop branch. we PR to features to develop and than merge develop to main to release new version

**Comment by ghost** [comment]
@garrylachman. Changed this PR to the develop branch.

**Comment by ghost** [comment]
@garrylachman Please consider merging the PR.

**Pull request closed without merging**
